version: '3.9'

services:
  web:
    build:
      dockerfile: ./Dockerfile
    command: ["./entrypoint.sh"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data: {}